const AttendenceData = [
  {
    id: 1,
    date: "Sat 8 Feb 2025",
    status: "Present",
    check_in: "9:30",
    check_out: "18:30",
    total_hours: "9 hrs",
  },
  {
    id: 2,
    date: "Sun 9 Feb 2025",
    status: "WeekOff",
    check_in: "--",
    check_out: "--",
    total_hours: "--",
  },
  {
    id: 3,
    date: "Mon 10 Feb 2025",
    status: "Present",
    check_in: "10:00",
    check_out: "19:00",
    total_hours: "9 hrs",
  },
  {
    id: 4,
    date: "Tue 11 Feb 2025",
    status: "Late",
    check_in: "11:00",
    check_out: "19:30",
    total_hours: "8.5 hrs",
  },
  {
    id: 5,
    date: "Wed 12 Mar 2025",
    status: "Half Day",
    check_in: "9:30",
    check_out: "13:30",
    total_hours: "4 hrs",
  },
  {
    id: 6,
    date: "Wed 12 Mar 2025",
    status: "Absent",
    check_in: "9:30",
    check_out: "13:30",
    total_hours: "4 hrs",
  },
  {
    id: 7,
    date: "Mon 10 Mar 2025",
    status: "Present",
    check_in: "10:00",
    check_out: "19:00",
    total_hours: "9 hrs",
  },
];

export default AttendenceData;
